### ISSUE TITLE
Special info for individual machines

### ISSUE THREAD

**Issue by bt2901** [bbchallenge/bbchallenge#16]
Currently, I can click at 
```Skelet's machine 1 ≈ Machine #68,329,601```

at the sidebar, be moved to the appropriate page but nothing on that page indicates that I'm looking at one of Skelet's holdouts. Ideally, at least some pages should contain additional information relevant to TM described.

Some ideas:
* this machine is a part of Skelet's 43 list
* this machine is a blanking / beeping beaver
* link to papers mentioning this TM
* link to a blog post analysing it's behaviour
* description of what it does (e.g. "counts in base 2 on one side and in base 3 on the other")

Also, some elementary statistics could be interesting as well: rate of tape growth, percentage of time the machine spends at each state, frequency of various state transition pairs.

**Comment by tcosmo** [comment]
This is solved, thanks to the wiki feature, thank you (see [Skelet 1](https://bbchallenge.org/68329601))

<img width="274" alt="Capture d’écran 2024-06-30 à 10 53 20" src="https://github.com/bbchallenge/bbchallenge/assets/7616128/d3b05e1b-d96c-40c0-b2b8-51ba87912ef3">
