### ISSUE TITLE
Bug - Explore mode can break the visualizer

### ISSUE THREAD

**Issue by int-y1** [bbchallenge/bbchallenge#26]
How to reproduce:

1. Go to https://bbchallenge.org/20569060
2. Toggle "Explore mode"
3. Under "Simulation Parameters", change "initial tape content" to "001"

Afterwards, the visualizer doesn't respond to any parameter changes, and a lot of buttons on the page stopped working. e.g. clicking "Go (R)andom" doesn't do anything.

**Comment by tcosmo** [comment]
Thank you for the bug report!

There is a Javascript error, c.f. attached screenshot. Probably related to the fact that the machine halts?

Maybe @Nathan-Fenner would have an idea?


![Screenshot from 2023-10-25 09-36-40](https://github.com/bbchallenge/bbchallenge/assets/7616128/14f2919d-6f97-422a-9d56-c0a6be23095a)

**Comment by Nathan-Fenner** [comment]
I've opened a fix for this in #27, I'm not sure exactly when it was introduced, but it's a simple fix. I'd like to eventually get TypeScript running in strict type-checking mode, because it could have caught this issue in advance.

**Comment by tcosmo** [comment]
Thank you very much!!
