### ISSUE TITLE
Machine code table has columns with different widths

### ISSUE THREAD

**Issue by int-y1** [bbchallenge/bbchallenge#33]
https://bbchallenge.org/1RB3RB---3LA1RA_2LA3RA4LB0LB0LA

![Screenshot 2024-06-27 183812](https://github.com/bbchallenge/bbchallenge/assets/14223529/ced15e91-97aa-47f8-bb45-1c244c8e6182)

Modify the table to have columns of equal width.

**Comment by tcosmo** [comment]
This is solved, thank you!
