### ISSUE TITLE
Get rid of base-64 representations for something simpler?

### ISSUE THREAD

**Issue by tcosmo** [bbchallenge/bbchallenge#6]
In [this code](http://discuss.bbchallenge.org/t/decider-backward-reasoning/35/3), [@atticuscull](https://github.com/atticuscull) has intuitively used strings such as `1RB0LD1LC0RE???1LD1LA1LD1RA0RA` for compact machine representations.

This representation is probably way simpler and requires less boilerplate than the current [base-64 representation](https://bbchallenge.org/story#base-64). 

I would be open to ditch [base-64 representation](https://bbchallenge.org/story#base-64) for something like that in order to remove unnecessary complexity in the project.

The only annoyance here is that `?` is not a URL-safe character. It could be replaced by `.` in URLs or in the entire project.

New direct links to machines could look like https://bbchallenge.org/1RB0LD1LC0RE...1LD1LA1LD1RA0RA

Do you have an opinion? @modderme123 [@atticuscull](https://github.com/atticuscull), [@pg132](https://github.com/pg132), [@DunDunDunDone](https://github.com/DunDunDunDone) @[EricESeverson](https://github.com/EricESeverson)

**Comment by modderme123** [comment]
I would be in favor of replacing `???` with `---`

**Comment by DunDunDunDone** [comment]
Just to clarify, the base-64 representation is just for humans to load Turing machines right?

**Comment by tcosmo** [comment]
Exactly, it is just a compact representation of any Turing machine, this converter convert a TM into its b64 representation: https://bbchallenge.org/base-64

But this representation is actually not very human friendly and a bit cumbersome to use (you have to decode and encode)

**Comment by tcosmo** [comment]
Done in #7
